mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dmsdbj.team.springbootdemo.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:p6spy:mysql://localhost:3306/test
      username: root
      password: 12345678
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      min-idle: 5
      initial-size: 5
      max-active: 20
      max-wait: 60000
      #      如果当前连接池中某个连接在空闲了timeBetweenEvictionRunsMillis时间后任然没有使用，则被物理性的关闭掉。
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        wall:
        enabled: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
server:
  port: 8081
  servlet:
    context-path: /spring-demo
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true


